---

oracle_install_user:             "oracle"
oracle_install_group:            "oinstall"
root_directory:                  "/u01"
src_scripts_dir:               "/etc/ansible/roles/racdb_upgrade/files"
oracle_base: /u01/app/oracle
old_oracle_home: /u01/app/oracle/product/12.2.0/db100
stage_dir: /u01/stage
scripts_dir:               " {{ stage_dir }}"
target_dbuname:  PMON1_01
target_dbname:  PMON1
root_user: root
oracle_sid: PMON11
new_oracle_home: /u02/app/oracle/product/18.3.0/dbhome_1
jdk_dir: /u02/app/oracle/product/18.3.0/dbhome_1/jdk
logdir: /tmp/18cCDBUPGRD/{{ oracle_sid }}
oratab:                         "/etc/oratab"
BLACKOUTNAME: "UPGRADE_DB_{{ target_dbuname }}"
RESTORE_POINT: "BEFORE_UPGRADE"
CLUSTER: "racdb01"
PDB_NAME: "PMON1PDB"
TZ_Version: "31"
